import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "ru" | "kz" | "en";

const translations = {
  ru: {
    // Layout
    nav_dashboard: "Дашборд",
    nav_registry: "Реестр",
    connect_wallet: "Подключить кошелёк",
    disconnect: "Отключить",
    lang_label: "Язык",
    // Dashboard
    page_title: "БИОМЕТРИЧЕСКИЙ ЦЕНТР УПРАВЛЕНИЯ",
    page_subtitle: "Национальный стандарт мониторинга здоровья. Телеметрия активна. ИИ-Оракул готов к автономной оценке.",
    system_status: "Статус системы",
    operational: "АКТИВНА",
    offline: "ОФЛАЙН",
    live_telemetry: "ТЕЛЕМЕТРИЯ В РЕАЛЬНОМ ВРЕМЕНИ",
    syncing: "СИНХРОНИЗАЦИЯ",
    heart_rate: "Пульс",
    daily_steps: "Шаги за день",
    sleep_quality: "Качество сна",
    hrs_duration: "ЧАС СНА",
    ai_oracle: "АНАЛИЗ ИИ-ОРАКУЛА",
    ai_oracle_sub: "Отправьте телеметрию для автономной оценки.",
    analyze_btn: "АНАЛИЗИРОВАТЬ ВИТАЛЬНЫЕ ПОКАЗАТЕЛИ",
    analyzing: "АНАЛИЗИРУЮ...",
    verdict_title: "АВТОНОМНЫЙ ВЕРДИКТ",
    awaiting: "ОЖИДАНИЕ ДАННЫХ",
    awaiting_sub: "Отправьте показатели для оценки ИИ и определения права на вознаграждение.",
    score_label: "БАЛЛ",
    reward_granted: "ВОЗНАГРАЖДЕНИЕ ОДОБРЕНО",
    reward_denied: "В ВОЗНАГРАЖДЕНИИ ОТКАЗАНО",
    ai_reasoning: "Обоснование ИИ",
    directives: "Директивы",
    claim_btn: "ПОЛУЧИТЬ НАГРАДУ (Solana Devnet)",
    claiming: "ВЫПОЛНЯЮ ТРАНЗАКЦИЮ...",
    connect_to_claim: "ПОДКЛЮЧИТЬ КОШЕЛЁК ДЛЯ ПОЛУЧЕНИЯ",
    tx_success: "Вознаграждение получено",
    tx_desc: "Transaction ID: ",
    view_explorer: "Просмотр в Solana Explorer",
    tx_id_label: "ID ТРАНЗАКЦИИ",
    // Registry
    registry_title: "РЕЕСТР РЕШЕНИЙ",
    registry_subtitle: "Неизменяемый реестр всех автономных выплат здоровья, выданных Bio-Sovereign AI.",
    total_paid: "Всего выплачено",
    rewards_issued: "Наград выдано",
    citizens: "Граждан",
    avg_score: "Средний балл здоровья",
    tx_log: "ЖУРНАЛ ТРАНЗАКЦИЙ",
    loading: "ЗАГРУЗКА РЕЕСТРА...",
    no_records: "ЗАПИСЕЙ В РЕЕСТРЕ НЕТ",
    col_date: "Дата",
    col_ai_decision: "Решение ИИ",
    col_tx: "Хеш транзакции Solana",
    col_score: "Балл",
    col_amount: "Сумма",
    view_tx: "Открыть",
  },
  kz: {
    nav_dashboard: "Бақылау тақтасы",
    nav_registry: "Тіркелім",
    connect_wallet: "Әмиянды қосу",
    disconnect: "Ажырату",
    lang_label: "Тіл",
    page_title: "БИОМЕТРИЯЛЫҚ БАСҚАРУ ОРТАЛЫҒЫ",
    page_subtitle: "Денсаулықты бақылаудың ұлттық стандарты. Телеметрия белсенді. ЖИ Оракулы дайын.",
    system_status: "Жүйе күйі",
    operational: "ЖҰМЫС ІСТЕЙДІ",
    offline: "ОФЛАЙН",
    live_telemetry: "НАҚТЫ УАҚЫТ ТЕЛЕМЕТРИЯСЫ",
    syncing: "СИНХРОНДАУ",
    heart_rate: "Жүрек соғу",
    daily_steps: "Күнделікті қадамдар",
    sleep_quality: "Ұйқы сапасы",
    hrs_duration: "СҒТ ҰЗАҚТЫҒЫ",
    ai_oracle: "ЖИ ОРАКУЛ ТАЛДАУЫ",
    ai_oracle_sub: "Автономды бағалау үшін телеметрия жіберіңіз.",
    analyze_btn: "БИОМЕТРИЯНЫ ТАЛДАУ",
    analyzing: "ТАЛДАУ ЖҮРІП ЖАТЫР...",
    verdict_title: "АВТОНОМДЫ ҮКІМ",
    awaiting: "ДЕРЕКТЕР КҮТІЛУДЕ",
    awaiting_sub: "Марапат алу мүмкіндігін анықтау үшін көрсеткіштерді жіберіңіз.",
    score_label: "БАЛЛ",
    reward_granted: "МАРАПАТ МАҚҰЛДАНДЫ",
    reward_denied: "МАРАПАТТАН БАС ТАРТЫЛДЫ",
    ai_reasoning: "ЖИ негіздемесі",
    directives: "Нұсқаулықтар",
    claim_btn: "МАРАПАТ АЛУ (Solana Devnet)",
    claiming: "ТРАНЗАКЦИЯ ОРЫНДАЛУДА...",
    connect_to_claim: "АЛУ ҮШІН ӘМИЯНДЫ ҚОСУ",
    tx_success: "Марапат алынды",
    tx_desc: "Transaction ID: ",
    view_explorer: "Solana Explorer-де қарау",
    tx_id_label: "ТРАНЗАКЦИЯ ИДЕНТИФИКАТОРЫ",
    registry_title: "ШЕШІМДЕР ТІРКЕЛІМІ",
    registry_subtitle: "Bio-Sovereign AI берген барлық марапаттардың өзгермейтін тіркелімі.",
    total_paid: "Барлығы төленді",
    rewards_issued: "Марапат берілді",
    citizens: "Азаматтар",
    avg_score: "Орташа денсаулық балы",
    tx_log: "ТРАНЗАКЦИЯ ЖУРНАЛЫ",
    loading: "ТІРКЕЛІМ ЖҮКТЕЛУДЕ...",
    no_records: "ТІРКЕЛІМДЕ ЖАЗБАЛАР ЖОҚ",
    col_date: "Күні",
    col_ai_decision: "ЖИ шешімі",
    col_tx: "Solana транзакция хэші",
    col_score: "Балл",
    col_amount: "Сома",
    view_tx: "Ашу",
  },
  en: {
    nav_dashboard: "Dashboard",
    nav_registry: "Registry",
    connect_wallet: "Connect Wallet",
    disconnect: "Disconnect",
    lang_label: "Language",
    page_title: "BIOMETRIC COMMAND CENTER",
    page_subtitle: "National Standard Health Monitoring System. Live telemetry link active. AI Oracle ready for autonomous evaluation.",
    system_status: "System Status",
    operational: "OPERATIONAL",
    offline: "OFFLINE",
    live_telemetry: "LIVE TELEMETRY",
    syncing: "SYNCING",
    heart_rate: "Heart Rate",
    daily_steps: "Daily Steps",
    sleep_quality: "Sleep Quality",
    hrs_duration: "HRS DURATION",
    ai_oracle: "AI ORACLE ANALYSIS",
    ai_oracle_sub: "Submit live telemetry for autonomous evaluation.",
    analyze_btn: "ANALYZE MY VITALS",
    analyzing: "ANALYZING...",
    verdict_title: "AUTONOMOUS VERDICT",
    awaiting: "AWAITING TELEMETRY",
    awaiting_sub: "Submit your vitals for AI evaluation to determine reward eligibility.",
    score_label: "SCORE",
    reward_granted: "AUTONOMOUS REWARD GRANTED",
    reward_denied: "REWARD DENIED",
    ai_reasoning: "AI Reasoning",
    directives: "Directives",
    claim_btn: "CLAIM AUTONOMOUS REWARD (Solana Devnet)",
    claiming: "EXECUTING TRANSACTION...",
    connect_to_claim: "CONNECT WALLET TO CLAIM",
    tx_success: "Reward Claimed",
    tx_desc: "Transaction ID: ",
    view_explorer: "View on Solana Explorer",
    tx_id_label: "TRANSACTION ID",
    registry_title: "DECISION REGISTRY",
    registry_subtitle: "Immutable ledger of all autonomous health rewards granted by the Bio-Sovereign AI.",
    total_paid: "Total Paid",
    rewards_issued: "Rewards Issued",
    citizens: "Citizens",
    avg_score: "Avg Health Score",
    tx_log: "TRANSACTION LOG",
    loading: "LOADING REGISTRY...",
    no_records: "NO RECORDS FOUND IN LEDGER",
    col_date: "Date",
    col_ai_decision: "AI Decision",
    col_tx: "Solana Transaction Hash",
    col_score: "Score",
    col_amount: "Amount",
    view_tx: "View",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (typeof translations)["ru"];
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("ru");
  const t = translations[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
