import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "ru" | "kz" | "en";

const translations = {
  ru: {
    nav_dashboard: "Центр управления",
    nav_registry: "Реестр",
    nav_statistics: "Статистика",
    nav_profile: "Профиль",
    connect_wallet: "Подключить кошелёк",
    disconnect: "Отключить",
    lang_label: "Язык",
    page_title: "БИОМЕТРИЧЕСКИЙ ЦЕНТР УПРАВЛЕНИЯ",
    page_subtitle: "Национальный стандарт мониторинга здоровья. Телеметрия активна. ИИ-Оракул готов к автономной оценке.",
    system_status: "Статус системы",
    operational: "АКТИВНА",
    offline: "ОФЛАЙН",
    live_telemetry: "ТЕЛЕМЕТРИЯ В РЕАЛЬНОМ ВРЕМЕНИ",
    syncing: "СИНХРОНИЗАЦИЯ",
    heart_rate: "Пульс",
    daily_steps: "Шаги за день",
    sleep_quality: "Качество сна",
    hrs_duration: "ЧАС СНА",
    ai_oracle: "АНАЛИЗ ИИ-ОРАКУЛА",
    ai_oracle_sub: "Отправьте телеметрию для автономной оценки.",
    analyze_btn: "АНАЛИЗИРОВАТЬ ВИТАЛЬНЫЕ ПОКАЗАТЕЛИ",
    analyzing: "АНАЛИЗИРУЮ...",
    verdict_title: "АВТОНОМНЫЙ ВЕРДИКТ",
    awaiting: "ОЖИДАНИЕ ДАННЫХ",
    awaiting_sub: "Отправьте показатели для оценки ИИ и определения права на вознаграждение.",
    score_label: "БАЛЛ",
    reward_granted: "ВОЗНАГРАЖДЕНИЕ ОДОБРЕНО",
    reward_denied: "В ВОЗНАГРАЖДЕНИИ ОТКАЗАНО",
    ai_reasoning: "Обоснование ИИ",
    directives: "Директивы",
    on_chain_action: "On-chain действие",
    claim_btn: "ПОЛУЧИТЬ НАГРАДУ (Solana Devnet)",
    claiming: "ВЫПОЛНЯЮ ТРАНЗАКЦИЮ...",
    connect_to_claim: "ПОДКЛЮЧИТЬ КОШЕЛЁК ДЛЯ ПОЛУЧЕНИЯ",
    tx_success: "Вознаграждение получено",
    tx_desc: "Transaction ID: ",
    view_explorer: "Просмотр в Solana Explorer",
    tx_id_label: "ID ТРАНЗАКЦИИ",
    registry_title: "РЕЕСТР РЕШЕНИЙ",
    registry_subtitle: "Неизменяемый реестр всех автономных выплат здоровья, выданных Bio-Sovereign AI.",
    total_paid: "Всего выплачено",
    rewards_issued: "Наград выдано",
    citizens: "Граждан",
    avg_score: "Средний балл",
    tx_log: "ЖУРНАЛ ТРАНЗАКЦИЙ",
    loading: "ЗАГРУЗКА РЕЕСТРА...",
    no_records: "ЗАПИСЕЙ В РЕЕСТРЕ НЕТ",
    col_date: "Дата",
    col_ai_decision: "Решение ИИ",
    col_tx: "Хеш транзакции Solana",
    col_score: "Балл",
    col_amount: "Сумма",
    view_tx: "Открыть",
    // Statistics
    stats_title: "АНАЛИТИКА ЗДОРОВЬЯ",
    stats_subtitle: "Долгосрочный мониторинг биометрических показателей. Анализ трендов ИИ.",
    period_day: "День",
    period_week: "Неделя",
    period_month: "Месяц",
    chart_score: "Индекс здоровья",
    chart_steps: "Шаги",
    chart_sleep: "Сон (качество)",
    chart_heart: "Пульс",
    ai_insight_title: "ИИ-РЕКОМЕНДАЦИИ",
    ai_insight_btn: "Получить рекомендации",
    ai_insight_loading: "ИИ анализирует тренды...",
    avg_score_label: "Средний балл",
    trend_label: "Тренд",
    best_label: "Лучший",
    worst_label: "Худший",
    // Profile
    profile_title: "ЛИЧНЫЙ КАБИНЕТ",
    profile_subtitle: "Управление профилем, страховка, кошелёк и подключённые устройства.",
    insurance_title: "СТРАХОВОЙ ПОЛИС",
    insurance_status: "Статус полиса",
    insurance_active: "Активен",
    insurance_discount: "Автономная скидка ИИ",
    insurance_based_on: "На основе",
    insurance_verdicts: "вердиктов",
    wallet_title: "КОШЕЛЁК SOL",
    wallet_balance: "Баланс",
    wallet_earned: "Заработано всего",
    wallet_txs: "Транзакций",
    pulsoma_title: "PULSOMA SYNC",
    pulsoma_btn: "Синхронизировать с Pulsoma",
    pulsoma_syncing: "Синхронизация...",
    pulsoma_synced: "Синхронизировано",
    pulsoma_desc: "Синхронизация с вашей медицинской картой",
    device_title: "ПОДКЛЮЧЁННЫЕ УСТРОЙСТВА",
    device_connect: "Подключить",
    device_connecting: "Подключение...",
    device_connected: "Подключено",
    device_disconnect: "Отключить",
    device_sync: "Синхр.",
    device_battery: "Батарея",
    device_last_sync: "Последняя синхронизация",
    device_none: "Нет подключённых устройств",
    device_none_sub: "Подключите ваши носимые устройства для расширенного мониторинга",
  },
  kz: {
    nav_dashboard: "Басқару орталығы",
    nav_registry: "Тіркелім",
    nav_statistics: "Статистика",
    nav_profile: "Профиль",
    connect_wallet: "Әмиянды қосу",
    disconnect: "Ажырату",
    lang_label: "Тіл",
    page_title: "БИОМЕТРИЯЛЫҚ БАСҚАРУ ОРТАЛЫҒЫ",
    page_subtitle: "Денсаулықты бақылаудың ұлттық стандарты. Телеметрия белсенді. ЖИ Оракулы дайын.",
    system_status: "Жүйе күйі",
    operational: "ЖҰМЫС ІСТЕЙДІ",
    offline: "ОФЛАЙН",
    live_telemetry: "НАҚТЫ УАҚЫТ ТЕЛЕМЕТРИЯСЫ",
    syncing: "СИНХРОНДАУ",
    heart_rate: "Жүрек соғу",
    daily_steps: "Күнделікті қадамдар",
    sleep_quality: "Ұйқы сапасы",
    hrs_duration: "СҒТ ҰЗАҚТЫҒЫ",
    ai_oracle: "ЖИ ОРАКУЛ ТАЛДАУЫ",
    ai_oracle_sub: "Автономды бағалау үшін телеметрия жіберіңіз.",
    analyze_btn: "БИОМЕТРИЯНЫ ТАЛДАУ",
    analyzing: "ТАЛДАУ ЖҮРІП ЖАТЫР...",
    verdict_title: "АВТОНОМДЫ ҮКІМ",
    awaiting: "ДЕРЕКТЕР КҮТІЛУДЕ",
    awaiting_sub: "Марапат алу мүмкіндігін анықтау үшін көрсеткіштерді жіберіңіз.",
    score_label: "БАЛЛ",
    reward_granted: "МАРАПАТ МАҚҰЛДАНДЫ",
    reward_denied: "МАРАПАТТАН БАС ТАРТЫЛДЫ",
    ai_reasoning: "ЖИ негіздемесі",
    directives: "Нұсқаулықтар",
    on_chain_action: "On-chain әрекет",
    claim_btn: "МАРАПАТ АЛУ (Solana Devnet)",
    claiming: "ТРАНЗАКЦИЯ ОРЫНДАЛУДА...",
    connect_to_claim: "АЛУ ҮШІН ӘМИЯНДЫ ҚОСУ",
    tx_success: "Марапат алынды",
    tx_desc: "Transaction ID: ",
    view_explorer: "Solana Explorer-де қарау",
    tx_id_label: "ТРАНЗАКЦИЯ ИДЕНТИФИКАТОРЫ",
    registry_title: "ШЕШІМДЕР ТІРКЕЛІМІ",
    registry_subtitle: "Bio-Sovereign AI берген барлық марапаттардың өзгермейтін тіркелімі.",
    total_paid: "Барлығы төленді",
    rewards_issued: "Марапат берілді",
    citizens: "Азаматтар",
    avg_score: "Орташа балл",
    tx_log: "ТРАНЗАКЦИЯ ЖУРНАЛЫ",
    loading: "ТІРКЕЛІМ ЖҮКТЕЛУДЕ...",
    no_records: "ТІРКЕЛІМДЕ ЖАЗБАЛАР ЖОҚ",
    col_date: "Күні",
    col_ai_decision: "ЖИ шешімі",
    col_tx: "Solana транзакция хэші",
    col_score: "Балл",
    col_amount: "Сома",
    view_tx: "Ашу",
    stats_title: "ДЕНСАУЛЫҚ ТАЛДАМАСЫ",
    stats_subtitle: "Биометриялық көрсеткіштерді ұзақ мерзімді бақылау.",
    period_day: "Күн",
    period_week: "Апта",
    period_month: "Ай",
    chart_score: "Денсаулық индексі",
    chart_steps: "Қадамдар",
    chart_sleep: "Ұйқы (сапасы)",
    chart_heart: "Жүрек соғу",
    ai_insight_title: "ЖИ ҰСЫНЫСТАРЫ",
    ai_insight_btn: "Ұсыныстар алу",
    ai_insight_loading: "ЖИ трендтерді талдауда...",
    avg_score_label: "Орташа балл",
    trend_label: "Тренд",
    best_label: "Үздік",
    worst_label: "Нашар",
    profile_title: "ЖЕКЕ КАБИНЕТ",
    profile_subtitle: "Профиль, сақтандыру, әмиян және қосылған құрылғыларды басқару.",
    insurance_title: "САҚТАНДЫРУ ПОЛИСІ",
    insurance_status: "Полис мәртебесі",
    insurance_active: "Белсенді",
    insurance_discount: "ЖИ автономды жеңілдігі",
    insurance_based_on: "Негізінде",
    insurance_verdicts: "үкімдер",
    wallet_title: "SOL ӘМИЯНЫ",
    wallet_balance: "Баланс",
    wallet_earned: "Барлығы табылды",
    wallet_txs: "Транзакциялар",
    pulsoma_title: "PULSOMA SYNC",
    pulsoma_btn: "Pulsoma-мен синхрондау",
    pulsoma_syncing: "Синхрондалуда...",
    pulsoma_synced: "Синхрондалды",
    pulsoma_desc: "Медициналық картаңызбен синхрондау",
    device_title: "ҚОСЫЛҒАН ҚҰРЫЛҒЫЛАР",
    device_connect: "Қосу",
    device_connecting: "Қосылуда...",
    device_connected: "Қосылды",
    device_disconnect: "Ажырату",
    device_sync: "Синхр.",
    device_battery: "Батарея",
    device_last_sync: "Соңғы синхрондау",
    device_none: "Қосылған құрылғылар жоқ",
    device_none_sub: "Кеңейтілген мониторинг үшін киілетін құрылғыларды қосыңыз",
  },
  en: {
    nav_dashboard: "Command Center",
    nav_registry: "Registry",
    nav_statistics: "Statistics",
    nav_profile: "Profile",
    connect_wallet: "Connect Wallet",
    disconnect: "Disconnect",
    lang_label: "Language",
    page_title: "BIOMETRIC COMMAND CENTER",
    page_subtitle: "National Standard Health Monitoring System. Live telemetry link active. AI Oracle ready for autonomous evaluation.",
    system_status: "System Status",
    operational: "OPERATIONAL",
    offline: "OFFLINE",
    live_telemetry: "LIVE TELEMETRY",
    syncing: "SYNCING",
    heart_rate: "Heart Rate",
    daily_steps: "Daily Steps",
    sleep_quality: "Sleep Quality",
    hrs_duration: "HRS DURATION",
    ai_oracle: "AI ORACLE ANALYSIS",
    ai_oracle_sub: "Submit live telemetry for autonomous evaluation.",
    analyze_btn: "ANALYZE MY VITALS",
    analyzing: "ANALYZING...",
    verdict_title: "AUTONOMOUS VERDICT",
    awaiting: "AWAITING TELEMETRY",
    awaiting_sub: "Submit your vitals for AI evaluation to determine reward eligibility.",
    score_label: "SCORE",
    reward_granted: "AUTONOMOUS REWARD GRANTED",
    reward_denied: "REWARD DENIED",
    ai_reasoning: "AI Reasoning",
    directives: "Directives",
    on_chain_action: "On-chain Action",
    claim_btn: "CLAIM AUTONOMOUS REWARD (Solana Devnet)",
    claiming: "EXECUTING TRANSACTION...",
    connect_to_claim: "CONNECT WALLET TO CLAIM",
    tx_success: "Reward Claimed",
    tx_desc: "Transaction ID: ",
    view_explorer: "View on Solana Explorer",
    tx_id_label: "TRANSACTION ID",
    registry_title: "DECISION REGISTRY",
    registry_subtitle: "Immutable ledger of all autonomous health rewards granted by the Bio-Sovereign AI.",
    total_paid: "Total Paid",
    rewards_issued: "Rewards Issued",
    citizens: "Citizens",
    avg_score: "Avg Score",
    tx_log: "TRANSACTION LOG",
    loading: "LOADING REGISTRY...",
    no_records: "NO RECORDS FOUND IN LEDGER",
    col_date: "Date",
    col_ai_decision: "AI Decision",
    col_tx: "Solana Transaction Hash",
    col_score: "Score",
    col_amount: "Amount",
    view_tx: "View",
    stats_title: "HEALTH ANALYTICS",
    stats_subtitle: "Long-term biometric monitoring. AI trend analysis.",
    period_day: "Day",
    period_week: "Week",
    period_month: "Month",
    chart_score: "Health Index",
    chart_steps: "Steps",
    chart_sleep: "Sleep (quality)",
    chart_heart: "Heart Rate",
    ai_insight_title: "AI RECOMMENDATIONS",
    ai_insight_btn: "Get recommendations",
    ai_insight_loading: "AI analyzing trends...",
    avg_score_label: "Avg Score",
    trend_label: "Trend",
    best_label: "Best",
    worst_label: "Worst",
    profile_title: "PERSONAL ACCOUNT",
    profile_subtitle: "Profile, insurance, wallet and connected devices management.",
    insurance_title: "INSURANCE POLICY",
    insurance_status: "Policy Status",
    insurance_active: "Active",
    insurance_discount: "AI Autonomous Discount",
    insurance_based_on: "Based on",
    insurance_verdicts: "verdicts",
    wallet_title: "SOL WALLET",
    wallet_balance: "Balance",
    wallet_earned: "Total Earned",
    wallet_txs: "Transactions",
    pulsoma_title: "PULSOMA SYNC",
    pulsoma_btn: "Sync with Pulsoma",
    pulsoma_syncing: "Syncing...",
    pulsoma_synced: "Synced",
    pulsoma_desc: "Synchronize with your medical record",
    device_title: "CONNECTED DEVICES",
    device_connect: "Connect",
    device_connecting: "Connecting...",
    device_connected: "Connected",
    device_disconnect: "Disconnect",
    device_sync: "Sync",
    device_battery: "Battery",
    device_last_sync: "Last sync",
    device_none: "No devices connected",
    device_none_sub: "Connect your wearable devices for enhanced monitoring",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (typeof translations)["ru"];
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("ru");
  const t = translations[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
